# Configuration file for MCE - LED brightness configuration for aw91xxx

# By default all leds use full hw range (0 ... 255)
[LEDBrightnesAW91XXX]
# Normalization example for: too dim green, too bright blue
#Red=72
#Orange=70
#Yellow=78
#Green=255
#Blue=10
