# Configuration file for MCE - LED Pattern configuration for aw91xxx
# -*- mode: sh -*-

# ----------------------------------------------------------------------------
# For led pattern to "exist", it must have standard hybris configuration
# ----------------------------------------------------------------------------

[LEDPatternHybris]

# Patterns used for the hybris hardware;
# Please prefix pattern names with Pattern to avoid name space clashes
#
# [0] Priority (0 - highest, 255 - lowest)
# [1] ScreenOn
#     0 only show pattern when the display is off
#     1 show pattern even when the display is on
#     2 only show pattern when the display is off, including acting dead
#     3 show pattern even when the display is on, including acting dead
#     4 only show pattern if the display is off, or if in acting dead
#     5 always show pattern, even if LED disabled
#     6 Like 0, but automatically disable after display on
#     7 show pattern even when the display is dim
# [2] Timeout in seconds before pattern is disabled, 0 for infinite
# [3] OnPeriod in milliseconds
# [4] OffPeriod in milliseconds
# [5] RGB24 as hexadecimal number


# - - - - - - - - - - - - - - - - - - - -
# Example standard pattern overrides
# - - - - - - - - - - - - - - - - - - - -

# Frame buffer does not go to sleep -> Blue
# (Default "Cyan" maps to Yellow / conflicts PatternDisplayResumeFailed)
#PatternDisplaySuspendFailed=11;5;0;100;100;0000ff

# Attempting to core dump lipstick -> Orange
# (Overred "Magenta" with the led that is not used for other display panics)
#PatternKillingLipstick=12;5;0;100;100;ff8000

# Device is booting up
# Constantly breathing red
#PatternPowerOn=10;3;0;500;500;ff0000


# Device is shutting down
# Constantly breathing Yellow
# (normally Red, but in reboot that can be confused with bootloader red)
#PatternPowerOff=8;3;0;500;5000;ffff00

# - - - - - - - - - - - - - - - - - - - -
# Example custom patterns
# - - - - - - - - - - - - - - - - - - - -

# When Bluetooth is in pairing state
# Constantly breathing blue
#PatternBluetoothInPairingMode=30;1;0;500;1500;0000ff

# When Bluetooth pairing completes
# Two breaths of green + auto-disable
#PatternBluetoothDeviceConnected=29;1;2;500;500;00ff00

# When Bluetooth unpairing completes
# One breath of red + auto-disable
#PatternBluetoothDeviceDisconnected=29;1;2;500;500;ff0000

# ----------------------------------------------------------------------------
# Hybris patterns can then be augmented with AW91XXX specific bytecode
#
# Note that for the sake of sw breathing policy the hybris pattern
# configuration should nave non-zero On/Off period.
# ----------------------------------------------------------------------------

[LEDPatternAW91XXX]

# Supported bytecode operations:
#
# L<led> 	LED 	   Selects led to target, value is:
#			    - 0/r => Red
#			    - 1/o    Orange
#			    - 2/y    Yellow
#			    - 3/g    Green
#			    - 4/b    Blue
#
# N		NOP	   No operation
#
# H		HALT       Terminates execution, current led level is retained
#
# R             RESTART    Restarts execution
#
# X             POWEROFF   Halts execution, led output is set to zero
#
# e<ms>         EXPIRY     Halt after specified time
#
# d<ms>         DELAY      Pauses for specified time, output is set to zero
#
# a<val>        AMPLITUDE  Define amplitude for the next FUNCTION (default=255)
#
# r<ms>         RISE_TIME  Define rise time for the next FUNCTION (default=0)
#
# h<ms>         HIGH_TIME  Define high time for the next FUNCTION (default=0)
#
# f<ms>         FALL_TIME  Define fall time for the next FUNCTION (default=0)
#
# l<ms>         LOW_TIME   Define low time for the next FUNCTION (default=0)
#
# c<val>        COUNT      Define repeat count for the next FUNCTION (default=0=infinite)
#
# F<func>       FUNCTION   Selects function to execute, value is:
#                           - f => Fixed, output is kept high
#                           - r    Rectangle, toggle between low and high states
#                           - t    Triangle, linear interpolation during rise / fall times
#                           - s    Sine, follows s-curve during rise / fall times
#
# Notes:
# - All <ms> values are quantized / EFFECT_TICK_MS - which is currently 50 ms.
# - Opearations are divided into immediate and have-waiting-state kinds and
#   bytecode executor halts if too long sequence of immedite operations is found.
#   (Basically the program needs to have FUNCTION operations too or it is rejected)
# - In case of breathing/blinking hybris pattern configuration, bytecode is generated
#   automatically if not explicitly provided in AW91XXX pattern config.
# - In case of device suspend, fallback to single color / hybris configuration is made.
# - In compilation phase, a separate program for each led is generated and these execute
#   in parallel, independent of each other.

# - - - - - - - - - - - - - - - - - - - -
# Example standard pattern overrides
# - - - - - - - - - - - - - - - - - - - -

# Chase from Red to Blue, then flash all leds
#PatternPowerOn=L0d0r100h100f100c1Fsd500r250f750c1Fsd1000RL1d100r100h100f100c1Fsd400r250f750c1Fsd1000RL2d200r100h100f100c1Fsd300r250f750c1Fsd1000RL3d300r100h100f100c1Fsd200r250f750c1Fsd1000RL4d400r100h100f100c1Fsd100r250f750c1Fsd1000R

# Chase from Blue to Red, then flash all leds
#PatternPowerOff=L0d400r100h100f100c1Fsd100r250f750c1Fsd1000RL1d300r100h100f100c1Fsd200r250f750c1Fsd1000RL2d200r100h100f100c1Fsd300r250f750c1Fsd1000RL3d100r100h100f100c1Fsd400r250f750c1Fsd1000RL4d0r100h100f100c1Fsd500r250f750c1Fsd1000R

# - - - - - - - - - - - - - - - - - - - -
# Example custom patterns
# - - - - - - - - - - - - - - - - - - - -

# Constantly Breathing blue
#PatternBluetoothInPairingMode=Lb r1000f1000Fs

# Fade in blue; two green flashes; fade out blue
#PatternBluetoothDeviceConnected=Lb r500h1000f500c1Fs Lg d500 h250l250c2Fr

# Fade in blue; one red flash; fade out blue
#PatternBluetoothDeviceDisconnected=Lb r500h500f500c1Fs Lr d500 h500c1Fr
